skip_local_validator = true

[toolchain]

[features]
resolution = true
skip-lint = false

[programs.devnet]
oneplan_vault = "HcBimMiXCgDnBabhsyoq99g1WqzNSEuiiNMoUvXrtLAL"

[programs.localnet]
oneplan_vault = "HcBimMiXCgDnBabhsyoq99g1WqzNSEuiiNMoUvXrtLAL"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/oneplan-devnet-authority.json"

[scripts]
test = "cargo test"

[hooks]
